plugins {
    id 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
    maven {
        name = 'Forge'
        url = 'https://maven.minecraftforge.net/'
    }
    maven {
        name = 'Terraformers'
        url = 'https://maven.terraformersmc.com/'
    }
    gradlePluginPortal()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

subprojects {
    group = rootProject.findProperty('maven_group')
    version = rootProject.findProperty('mod_version')

    tasks.withType(AbstractArchiveTask).configureEach {
        archiveBaseName = "${rootProject.name}-${project.name}"
    }
}
