plugins {
	id 'base'
}

subprojects {
	group = rootProject.findProperty('maven_group')
	version = rootProject.findProperty('mod_version')

	tasks.withType(AbstractArchiveTask).configureEach {
		archiveBaseName = "${rootProject.name}-${rootProject.findProperty('mod_version')}-${project.name}"
		archiveVersion = rootProject.findProperty('minecraft_version_range')
	}
}