pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'MinecraftForge'
			url = 'https://maven.minecraftforge.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
	// id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'collision-effects'

include('common')
include('fabric')
include('forge')