modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/salty5844/collision-effects/issues"

[[mods]]
modId="collision_effects"
version="${version}"
displayName="Collision Effects"
description='''See every impact! - HUD particle effects for impacts and environmental interactions'''
logoFile="icon.png"
authors="salty5844"
credits="Brandon Hartsock - Design, Ciera Marshall - Concept, Zoey Smith - Design"
displayURL="https://www.salty5844.com/"

[[dependencies.collision_effects]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.collision_effects]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="CLIENT"

[[mixins]]
config="collision-effects.mixins.json"
