plugins {
    id 'groovy-gradle-plugin'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    implementation 'net.fabricmc:fabric-loom:1.2.8'
}

